### ISSUE TITLE
Feedback data-dashboard

### ISSUE THREAD

**Issue by nadiatapm** [ValeriaCossio/scl-2018-05-bc-core-pm-datadashboard#4]
Les dejo el feedback de los avances que tienen hasta ahora en su repositorio.
*Les recomiendo subir sus cambios, para evitar tener problemas a la hora de subir sus cambios.*
no puedo darles feedback si no están sus repositorios actualizados.
de todas maneras les recuerdo que deben usar las etiquetas de html semántico para mantener el orden y buenas practicas en su código.
agreguen funcionalidad  a los elementos de su archivo js.
:muscle: :+1:

**Comment by ValeriaCossio** [comment]
Estamos trabajando para eso
